hub:
  # Dummy token for testing
  cookieSecret: 773305e0ba1846ea2e3f1010e094c05d4ed2ab295f9a4e2fa59fbf58f326b46b
  imagePullPolicy: IfNotPresent
  extraConfig:
    jupyter_notebook_config.py: |
      config = '/etc/jupyter/jupyter_notebook_config.py'

proxy:
  # Dummy token for testing
  secretToken: 773305e0ba1846ea2e3f1010e094c05d4ed2ab295f9a4e2fa59fbf58f326b46b
  service:
    # NodePort during development
    type: NodePort

singleuser:
  extraEnv:
    # Kubernetes internal DNS for services:
    # <svc-name>.<namespace>.svc.cluster.local
    KG_URL: "http://enterprise-gateway.enterprise-gateway.svc.cluster.local:8888"
    #KG_HTTP_USER: "{username}"
    #KERNEL_USERNAME: "{username}"
    KG_REQUEST_TIMEOUT: "60"
  image:
    name: gurkamal/jupyter-k8s-single-user-for-enterprise-gateway
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  storage:
    dynamic:
      storageClass: "aws-efs"
      pvcNameTemplate: "{username}"
      volumeNameTemplate: "{username}"
      storageAccessModes: 
      - "ReadWriteMany"

