hub
  image:
    name: gurkamal/jupyter-k8s-hub-for-mongodb
    tag: '0.8.2':
  # Dummy token for testing
  cookieSecret: 773305e0ba1846ea2e3f1010e094c05d4ed2ab295f9a4e2fa59fbf58f326b46b
  # imagePullPolicy: IfNotPresent
  extraConfig:
    podConfig.py: |
      a_local = "sam"
      c.KubeSpawner.namespace = a_local 

auth:
  type: github
  github:
    clientId: "b1101eb691035876e278"
    clientSecret: "2a4b4fde0212a2801856410920380b644f4fcd25"
    callbackUrl: "http://ec2-34-204-94-178.compute-1.amazonaws.com:30000/hub/oauth_callback"
proxy:
  # Dummy token for testing
  secretToken: 773305e0ba1846ea2e3f1010e094c05d4ed2ab295f9a4e2fa59fbf58f326b46b
  service:
    # NodePort during development
    type: NodePort
    nodePorts:
      http: 30000
      https: 30001
    #singleuser:
    # extraEnv:
    # KG_URL: "http://100.71.229.192:8888"
    # KG_HTTP_USER: "{username}"
    # KERNEL_USERNAME: "{username}"
    # KG_REQUEST_TIMEOUT: "60"
# image:
  # name: gurkamal/jupyter-k8s-single-user-for-enterprise-gateway
  # tag: '0.8.2'
  # pullPolicy: IfNotPresent
  storage:
    dynamic:
      storageClass: "aws-efs"
      pvcNameTemplate: "{username}"
      volumeNameTemplate: "{username}"
      storageAccessModes: 
      - "ReadWriteMany"

