apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: jupyterhub
    chart: jupyterhub-0.8.2
    component: hub
    heritage: Helm
    release: jupyterhub-dev
  name: hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jupyterhub
